add ugly html table for stock data, still need tests
JessicaGreben/snp pull request #6
Opened 2017-04-04 04:01 UTC by JessicaGreben

2017-04-07 17:19 UTC, ryanloughlin25 requested changes
I'm liking github's review system less and less.  Some of my comments are just comments or questions and some of them are for requesting changes, but I have to either approve or request changes for the whole thing at once.

The ones that I am request changes for are the if statement and the exception.  The rest are just discussion.

2017-04-07 17:19 UTC, ryanloughlin25 commented on app/test/test_server.py
> +	with pGetRecentOhlvc:
I've never seen a context manager stored in a variable and then used on the following line.  I don't have an opinion whether that's good or bad.  why did you do it that way?

2017-04-07 17:19 UTC, ryanloughlin25 commented on app/test/test_server.py
> +	pGetRecentOhlvc = patch.object(db, 'get_recent_ohlvc', return_value='stuff')
why is `pGetRecentOhlvc` CamelCase rather than snake_case?

2017-04-07 17:19 UTC, ryanloughlin25 commented on app/db.py
> +        return False
`delta_days != 0` already returns `True` or `False`.  That's how the if statement knows which way to branch.
The if statement can be replaces with `return delta_days != 0`.

Also I think it should be fine, but it's worth considering.  What does this function do if it is somehow run when data is in the database for a future date?  (the data is fake, a test is using [freezegun](https://github.com/spulec/freezegun), etc.)

2017-04-07 17:19 UTC, ryanloughlin25 commented on app/server.py
> +    except:
Do you know the type of the exception you are catching?  This will catch literally everything, even keyboard interrupts.

2017-04-07 17:19 UTC, ryanloughlin25 commented on app/server.py
> +    if db.symbol_exists(symbol):
I'm not sure I understand the purpose of this line.  It looks like it only allows the user to update data for symbols that already exist in the database?  Can a user not request a symbol that is valid (i.e. quandl knows the symbol), but that this application has not seen yet?  If not, how do new symbols get added to the application?

2017-04-07 17:19 UTC, ryanloughlin25 commented on app/templates/dailystock.html
> +	    <td>{{ data[7] }}</td>
The db's and html's use of the ohlcv data are tightly coupled.  At some point (could be the db, or the api, or the front-end depending), the data should probably be reformatted into a more generic format.  We should talk more about it, but it's fine for now.

2017-04-07 17:40 UTC, JessicaGreben commented on app/db.py
> +        return False
omg I am so annoyed with my brain, I am always doing this with the True/ False when the statement already evaluates to that.

2017-04-07 22:05 UTC, JessicaGreben commented on app/test/test_server.py
> +	pGetRecentOhlvc = patch.object(db, 'get_recent_ohlvc', return_value='stuff')
cause we use camel case at work, but i want to use snake case here and my brain flip flops between the two. lol.

2017-04-07 22:07 UTC, JessicaGreben commented on app/test/test_server.py
> +	with pGetRecentOhlvc:
what do you mean by 'context manager'?  i put in in a variable cause I thought it was too long and thought that 
`with patch.object(db, 'get_recent_ohlvc', return_value='stuff')` was ulgy and less readable.  I don't know which is better.  Consistency is best maybe? And I flip flop I think.

2017-04-07 22:09 UTC, JessicaGreben commented on app/templates/dailystock.html
> +	    <td>{{ data[7] }}</td>
hmm good point.  yeah i am a little confused about the data flow and manipulation in this app so far.  This data will need to be reformatted to use D3 anyhow, so I will get forced to do that, but I don't know what is the best way.  I would like to talk more about this with you, I think I have some big knowledge gaps here.

2017-04-07 22:10 UTC, JessicaGreben commented on app/server.py
> +    except:
good point, I will add the specific exception to this

2017-04-07 22:12 UTC, JessicaGreben commented on app/server.py
> +    if db.symbol_exists(symbol):
good catch. yeah i was checking if the symbol was in the db, but you are right... I actually want to make an API call to get the data if the symbol is not in the db.  I will update this.

2017-04-07 23:47 UTC, ryanloughlin25 commented on app/test/test_server.py
> +	with pGetRecentOhlvc:
a context manager is the name for an object that can be used with the `with` statement.  see [pep 343](https://www.python.org/dev/peps/pep-0343/) for more info.  One thing that occurs to me is that the context manager is expected to exit in some way at the end of the `with` block.  I wonder if the variable is still valid after the `with` block or not.  I need to play with it a bit to learn more about how it behaves.

2017-04-10 02:04 UTC, ryanloughlin25 requested changes
I tested manually this time by pulling your branch and running the website locally.  The page works well.  I can see the most recent ohlcv data or an error message depending on my input.

I want to request one small change because I had to navigate to the new page via url.  There should be a link on the home page or in the nav bar or somewhere to navigate to the `/dailystock` page.

2017-04-10 02:04 UTC, ryanloughlin25 commented on app/db.py
> +    todays_day = date(todays_date.year, todays_date.month, todays_date.day)
`date.today()` is available in addition to `datetime.today()`.  see https://docs.python.org/2/library/datetime.html#datetime.date.today

2017-04-12 01:38 UTC, ryanloughlin25 approved these changes

2017-04-12 01:44 UTC, merged